# Generated by Django 3.0.5 on 2020-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank='true', null='true', upload_to='members_profile'),
        ),
    ]
